# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  release:
    types: [created]
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build Docker image
      run: docker build --tag kappsegla/test:${{ steps.get_version.outputs.VERSION }} .
    - name: Push Docker image
      run: |
        docker login -u ${{github.DOCKER_NAME}} -p ${{github.DOCKER_TOKEN}}
        docker push kappsegla/test:${{ steps.get_version.outputs.VERSION }}
